# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_creator', to='dashboard1.Post'),
        ),
    ]
